### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by veryeasily** [CommunityForge/www#17]
just wanted to say hi! hadn't done that in a while!

**Comment by mynameisfiber** [comment]
Hi

**Comment by veryeasily** [comment]
@mynameisfiber could you assign this issue to @wannabeCitizen

**Comment by wannabeCitizen** [comment]
Hi everyone, yinz 2 are good friends whom I appreciate :)

**Comment by murrayju** [comment]
Closing as not an issue. For help and discussion, please use our slack channel :nerd_face:
