### ISSUE TITLE
Add/Remove Resident Listings

### ISSUE THREAD

**Issue by cameronjj** [CommunityForge/www#21]
Images located here: https://drive.google.com/drive/folders/1BzlM7dp_OpTUPJJjV4u_G4i3aqHT0TDl?usp=sharing
Info located here: https://docs.google.com/spreadsheets/d/1xLvSbctkGbeyJ9wQmt-wWl6N5zQ_wvx7OizTK7k_dy8/edit?usp=sharing

(I am still working to get some of this information from tenants.

Add
- [x] Eastburgh Avengers Baseball Club
- [x] Opening doors for youth and families
- [x] Paramount Co-op
- [x] GCAP
- [x] Shane Pilster
- [x] Abigail Lis-Perlis
- [x] 15208 Productionz
- [x] Sunday Assembly
- [x] Golden Pillow Project

Remove
- [x] House of JeanMarie
- [x] Bob Ziller

**Comment by mynameisfiber** [comment]
I added most of the above residents with whatever information was available at the time on the spreadsheet. Ping me when more information is ready!

**Comment by cameronjj** [comment]
- [ ] Change GoPhleb logo to the new one

**Comment by cameronjj** [comment]
For the organizations with missing information, we should just add them with a placeholder CF logo, no text.  That way they're at least listed.

**Comment by cameronjj** [comment]
- [ ] Add PCO Technology Solutions to coworking

**Comment by cameronjj** [comment]
- [ ] New logo for 15208

**Comment by mynameisfiber** [comment]
@cameronjj can you check that everything is good on the website and, if so, close this issue? :1st_place_medal:
