### ISSUE TITLE
Add/Remove Tenant Info

### ISSUE THREAD

**Issue by cameronjj** [CommunityForge/www#26]
- [ ]  Add weblink to DSA: pghdsa.org
- [ ] Change Eastburgh Avengers Logo
- [ ] Remove Great Commission and Advanced Placement
- [ ] Remove The Entertainment Consortium
- [ ] Remove Khalil Malik
- [ ] Change GoPhleb description
- [ ] Add Notary One to Coworking
- [ ] Add PCO Technologies

- [ ] Change to Organization Section: Opening Doors for Youth and Families 
- [ ]  Change to Organization Section: GoPhleb
- [ ] Change to Organization Section: Notary One

- [ ] Add A Unique Brand
- [ ] Add Wilkinsburg Athletic Association
- [ ] Add Cynthia Clayton
- [ ] Add Ogechi Chieke
- [ ] Add Breathe Easy Independent Living Services

https://docs.google.com/spreadsheets/d/1xLvSbctkGbeyJ9wQmt-wWl6N5zQ_wvx7OizTK7k_dy8/edit?usp=sharing

**Comment by mynameisfiber** [comment]
This is now automatic
